"""
ComicCraft – PDF Exporter Module
Generates a professional multi-page comic PDF using FPDF.
Each page = one comic panel with title, image, scene, caption, narration, dialogue.
"""

import os
from datetime import datetime
from pathlib import Path
from fpdf import FPDF

# ─── Output directory ─────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
EXPORTS_DIR = BASE_DIR / "static" / "exports"
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

# ─── Comic color palette ──────────────────────────────────────────────
COLOR_BG_DARK   = (15,  23,  42)    # Deep navy
COLOR_ACCENT    = (220, 38,  127)   # Hot pink / comic magenta
COLOR_ACCENT2   = (99,  102, 241)   # Indigo
COLOR_WHITE     = (255, 255, 255)
COLOR_LIGHT     = (226, 232, 240)
COLOR_DARK_GRAY = (30,  41,  59)
COLOR_MID_GRAY  = (71,  85,  105)


def _clean_text(text: str) -> str:
    """Sanitize text to be strictly compatible with FPDF (Latin-1 / ASCII)."""
    if not text:
        return ""
    if not isinstance(text, str):
        text = str(text)

    # Common unicode replacements
    replacements = {
        "\u2018": "'", "\u2019": "'", "\u201a": "'", "\u201b": "'",
        "\u201c": '"', "\u201d": '"', "\u201e": '"', "\u201f": '"',
        "\u2013": "-", "\u2014": "-", "\u2015": "-", "\u2212": "-",
        "\u2026": "...",
        "\u2022": "-", "\u2023": "-", "\u25e6": "-",
        "\u00a0": " ",
        "⭐": "*", "✨": "*", "🎨": "*", "🤖": "*", "💻": "*", "🦸": "*",
        "🎉": "*", "📖": "*", "🎭": "*", "🌍": "*", "🔥": "*", "⚡": "*",
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)

    return text.encode("latin-1", "replace").decode("latin-1")


class ComicPDF(FPDF):
    """Custom FPDF subclass with comic-book styling."""

    def __init__(self, comic_title: str = "ComicCraft Story"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.comic_title = _clean_text(comic_title)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        """Top header bar on every page."""
        # Dark bar
        self.set_fill_color(*COLOR_BG_DARK)
        self.rect(0, 0, 210, 14, "F")
        # Accent line
        self.set_fill_color(*COLOR_ACCENT)
        self.rect(0, 13, 210, 2, "F")
        # App name
        self.set_xy(0, 2)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(105, 10, "COMICCRAFT", align="L", ln=0)
        # Story title
        self.set_text_color(*COLOR_LIGHT)
        self.cell(105, 10, self.comic_title[:50], align="R", ln=1)

    def footer(self):
        """Bottom footer bar on every page."""
        self.set_y(-14)
        self.set_fill_color(*COLOR_BG_DARK)
        self.rect(0, self.get_y(), 210, 15, "F")
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*COLOR_MID_GRAY)
        self.cell(0, 10, f"Generated by ComicCraft  -  Page {self.page_no()}", align="C")

    # ─── Helper drawing utilities ──────────────────────────────────────

    def _section_label(self, label: str, x: float, y: float, w: float):
        """Small coloured section label."""
        label = _clean_text(label)
        self.set_xy(x, y)
        self.set_fill_color(*COLOR_ACCENT2)
        self.set_text_color(*COLOR_WHITE)
        self.set_font("Helvetica", "B", 7)
        self.cell(w, 5, f"  {label.upper()}  ", fill=True, ln=1)

    def _body_text(self, text: str, x: float, y: float, w: float, color=None):
        """Render multi-line body text."""
        text = _clean_text(text)
        color = color or COLOR_LIGHT
        self.set_xy(x, y)
        self.set_text_color(*color)
        self.set_font("Helvetica", "", 9)
        self.multi_cell(w, 5, text)

    def _speech_bubble(self, speaker: str, text: str, x: float, y: float, w: float) -> float:
        """Render a speech bubble. Returns new Y position after bubble."""
        speaker = _clean_text(speaker)
        text = _clean_text(text)
        # Bubble background
        self.set_fill_color(*COLOR_DARK_GRAY)
        h = max(12, len(text) // 45 * 6 + 12)
        self.set_xy(x, y)
        self.rect(x, y, w, h + 6, "F")
        # Accent left strip
        self.set_fill_color(*COLOR_ACCENT)
        self.rect(x, y, 3, h + 6, "F")
        # Speaker name
        self.set_xy(x + 5, y + 1)
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(w - 5, 4, speaker.upper())
        # Speech text
        self.set_xy(x + 5, y + 6)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*COLOR_WHITE)
        self.multi_cell(w - 8, 4, f'"{text}"')
        return self.get_y() + 3


def save_pdf(layout: list[dict], story_title: str = "My Comic Story") -> str:
    """
    Generate a PDF from the comic layout list.

    Returns the relative static path: /static/exports/<filename>.pdf
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"comic_{timestamp}.pdf"
    out_path = EXPORTS_DIR / filename

    pdf = ComicPDF(comic_title=story_title)

    # ─── Cover page ───────────────────────────────────────────────────
    pdf.add_page()

    # Dark full background
    pdf.set_fill_color(*COLOR_BG_DARK)
    pdf.rect(0, 0, 210, 297, "F")

    # Decorative vertical stripes
    pdf.set_fill_color(30, 40, 65)
    for i in range(0, 210, 30):
        pdf.rect(i, 0, 15, 297, "F")

    # Title box
    pdf.set_fill_color(*COLOR_ACCENT)
    pdf.rect(20, 80, 170, 4, "F")
    pdf.rect(20, 160, 170, 4, "F")

    # App name
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(*COLOR_ACCENT)
    pdf.set_xy(0, 95)
    pdf.cell(210, 20, "COMICCRAFT", align="C", ln=1)

    # Subtitle
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(*COLOR_LIGHT)
    pdf.set_xy(0, 120)
    pdf.cell(210, 10, "AI Comic Story Creator", align="C", ln=1)

    # Story title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*COLOR_WHITE)
    pdf.set_xy(20, 170)
    pdf.multi_cell(170, 12, _clean_text(story_title), align="C")

    # 5 Panel count
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*COLOR_ACCENT2)
    pdf.set_xy(0, 230)
    pdf.cell(210, 8, f"A {len(layout)}-Panel Comic Adventure", align="C", ln=1)

    # Timestamp
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*COLOR_MID_GRAY)
    pdf.set_xy(0, 270)
    pdf.cell(210, 6, f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", align="C")

    # ─── Panel pages ──────────────────────────────────────────────────
    for panel in layout:
        pdf.add_page()

        # Dark background
        pdf.set_fill_color(*COLOR_BG_DARK)
        pdf.rect(0, 0, 210, 297, "F")

        margin_x = 12
        content_w = 210 - margin_x * 2
        y = 18  # Start below header

        # ── Panel number badge ────────────────────────────────────────
        pdf.set_fill_color(*COLOR_ACCENT)
        pdf.rect(margin_x, y, 12, 12, "F")
        pdf.set_xy(margin_x, y)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*COLOR_WHITE)
        pdf.cell(12, 12, str(panel["panel_number"]), align="C")

        # ── Panel title ────────────────────────────────────────────────
        pdf.set_xy(margin_x + 14, y + 1)
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(*COLOR_WHITE)
        pdf.cell(content_w - 14, 10, _clean_text(panel["title"])[:60])
        y += 16

        # ── Accent line ────────────────────────────────────────────────
        pdf.set_fill_color(*COLOR_ACCENT)
        pdf.rect(margin_x, y, content_w, 1.5, "F")
        y += 4

        # ── Panel image ────────────────────────────────────────────────
        img_h = 80  # Image height in mm
        img_w = content_w
        image_abs = BASE_DIR / panel["image_path"].lstrip("/").replace("/", os.sep)

        if image_abs.exists():
            try:
                pdf.image(str(image_abs), x=margin_x, y=y, w=img_w, h=img_h)
            except Exception:
                _draw_image_error_box(pdf, margin_x, y, img_w, img_h, panel.get("image_error"))
        else:
            _draw_image_error_box(pdf, margin_x, y, img_w, img_h, "Image file not found")

        # Image border
        pdf.set_draw_color(*COLOR_ACCENT)
        pdf.rect(margin_x, y, img_w, img_h, "D")
        y += img_h + 4

        # ── Caption ────────────────────────────────────────────────────
        if panel.get("caption"):
            pdf.set_fill_color(*COLOR_DARK_GRAY)
            pdf.rect(margin_x, y, content_w, 9, "F")
            pdf.set_xy(margin_x + 3, y + 1)
            pdf.set_font("Helvetica", "BI", 9)
            pdf.set_text_color(*COLOR_ACCENT)
            clean_cap = _clean_text(panel['caption'])[:100]
            pdf.cell(content_w - 6, 7, f"> {clean_cap}")
            y += 12

        # ── Scene Description ──────────────────────────────────────────
        pdf._section_label("Scene", margin_x, y, content_w)
        y = pdf.get_y() + 1
        pdf._body_text(panel.get("scene_description", ""), margin_x + 2, y, content_w - 4, COLOR_LIGHT)
        y = pdf.get_y() + 3

        # ── Narration ─────────────────────────────────────────────────
        pdf._section_label("Narration", margin_x, y, content_w)
        y = pdf.get_y() + 1
        pdf._body_text(panel.get("narration", ""), margin_x + 2, y, content_w - 4, COLOR_LIGHT)
        y = pdf.get_y() + 3

        # ── Dialogue bubbles ──────────────────────────────────────────
        dialogues = panel.get("dialogue", [])
        if dialogues:
            pdf._section_label("Dialogue", margin_x, y, content_w)
            y = pdf.get_y() + 1
            for bubble in dialogues[:4]:  # Max 4 bubbles per page
                y = pdf._speech_bubble(bubble["speaker"], bubble["text"], margin_x + 2, y, content_w - 4)
                if y > 270:
                    break

    # ─── Save ──────────────────────────────────────────────────────────
    pdf.output(str(out_path))
    return f"/static/exports/{filename}"


def _draw_image_error_box(pdf: FPDF, x: float, y: float, w: float, h: float, msg: str = None):
    """Draw a styled placeholder box when the image file is missing."""
    pdf.set_fill_color(20, 30, 55)
    pdf.rect(x, y, w, h, "F")
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(99, 102, 241)
    pdf.set_xy(x, y + h / 2 - 6)
    pdf.cell(w, 8, "[ Comic Panel Image ]", align="C")
    if msg:
        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(100, 120, 150)
        pdf.set_xy(x, y + h / 2 + 4)
        pdf.cell(w, 5, str(msg)[:80], align="C")
